module.exports = [
    "",
    "dog",
    "cat",
    "mom",
    "dad",
    "sister",
    "brother",
    "neighbor",
    "roommate",
    "landlord",
    "building",
    "aunt",
    "uncle",
    "cousin",
    "girlfriend",
    "boyfriend",
    "partner",
    "boss",
    "coworker",
    "manager",
    "teacher",
    "homework ",
    "friend",
    "hamster",
    "ghost in the attic",
    "car",
    "long-lost twin",
    "niece",
    "nephew",
    "local weather"
]
